{% set name = "datascience" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/24/c8/171ab6562bca1fa3ae6931a59068e9195be7e7399167f3d2573ee1c87486/datascience-0.18.0.tar.gz
  sha256: 0fae1517b6d77d4554e1a1fd1eea9118ebaca142689b2f6576ab0e8612c9f756

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pytest
    - pip
  run:
    - python >=3.6
    - folium >=0.9.1
    - setuptools
    - matplotlib-base >=3.0.0
    - pandas
    - scipy
    - numpy
    - ipython
    - plotly
    - branca

test:
  imports:
    - datascience
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/data-8/datascience
  summary: A Jupyter notebook Python library for introductory data science
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - whyvineet
