package:
  name: datascience
  version: 0.18.0
source:
  url: https://pypi.org/packages/source/d/datascience/datascience-0.18.0.tar.gz
  sha256: 0fae1517b6d77d4554e1a1fd1eea9118ebaca142689b2f6576ab0e8612c9f756

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0

requirements:
  host:
    - python >=3.6
    - pytest
    - setuptools
    - pip
    - importlib-metadata  # [py<38]
  run:
    - python >=3.6
    - folium >=0.9.1
    - setuptools
    - matplotlib-base >=3.0.0
    - pandas
    - scipy
    - numpy
    - ipython
    - plotly
    - branca
    - importlib-metadata  # [py<38]

test:
  imports:
    - datascience
  commands:
    - pip check
  requires:
    - pip
    - python >=3.6
    - pytest

about:
  home: https://github.com/data-8/datascience
  summary: A Jupyter notebook Python library for introductory data science
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yuvipanda
