{% set name = "datascience" %}
{% set version = "0.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datascience-{{ version }}.tar.gz
  sha256: 233a2f70ce940980f7a8b88ab76c501e5518766d5d8dffc6ec53d0449c399faf

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pytest
    - setuptools
    - pip
    - importlib-metadata
  run:
    - python >={{ python_min }}
    - folium >=0.9.1
    - setuptools
    - matplotlib-base >=3.0.0
    - pandas
    - scipy
    - numpy
    - ipython
    - plotly
    - branca
    - importlib-metadata

test:
  imports:
    - datascience
  commands:
    - pip check
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/data-8/datascience
  summary: A Jupyter notebook Python library for introductory data science
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yuvipanda
    - pancakereport
    - davidwagner
