{% set name = "datascience" %}
{% set version = "0.18.0" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datascience-{{ version }}.tar.gz
  sha256: 0fae1517b6d77d4554e1a1fd1eea9118ebaca142689b2f6576ab0e8612c9f756

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pytest
    - setuptools
    - pip
    - importlib-metadata  # [py<38]
  run:
    - python {{ python_min }}
    - folium >=0.9.1
    - setuptools
    - matplotlib-base >=3.0.0
    - pandas
    - scipy
    - numpy
    - ipython
    - plotly
    - branca
    - importlib-metadata  # [py<38]

test:
  imports:
    - datascience
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - pytest

about:
  home: https://github.com/data-8/datascience
  summary: A Jupyter notebook Python library for introductory data science
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yuvipanda
